import { describe, it, afterEach } from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import { NPC_SHEETS, drawNpcSheet, _setSheetImage } from '../renderer/render/npc-sheets.js'
import { drawEntity } from '../renderer/render/canvas.js'
import { makeNpc } from '../renderer/systems/npc.js'
import { tickNpcAnim, STRIDE } from '../renderer/systems/npc-anim.js'
import { NPC_SPECIES } from '../renderer/data/npcs.js'
import { SHEET } from '../renderer/assets/npcs/wolf-sheet.js'
import { readPng } from '../tools/png-read.mjs'

function recordingCtx() {
  const target = { ops: [], globalAlpha: 1, fillStyle: '' }
  return new Proxy(target, {
    get(t, k) { if (k in t) return t[k]; return (...a) => { t.ops.push([k, ...a]) } },
    set(t, k, v) { t[k] = v; return true },
  })
}
const fakeSheet = { complete: true, naturalWidth: SHEET.cellW * 7, naturalHeight: SHEET.cellH * 3 }
const S = 32
const wolfAt = (x, y, over = {}) => ({ ...makeNpc({ species: 'wolf', id: 'npc:t:0', x, y }), ...over })

describe('wolf sheet asset', () => {
  it('the generated sheet on disk matches its metadata and the species points at it', () => {
    const png = readPng('renderer/assets/npcs/wolf.png')
    const cols = Math.max(...Object.values(SHEET.rows).map(r => r.frames))
    assert.equal(png.width, SHEET.cellW * cols)
    assert.equal(png.height, SHEET.cellH * Object.keys(SHEET.rows).length)
    assert.deepEqual(Object.keys(SHEET.rows), ['walk', 'run', 'bite'])
    assert.equal(SHEET.rows.walk.frames + SHEET.rows.run.frames + SHEET.rows.bite.frames, 12, 'all twelve concept frames')
    assert.ok(png.pixels.some((v, i) => i % 4 === 3 && v === 0), 'sheet has transparent pixels')
    assert.ok(fs.readFileSync('renderer/assets/npcs/wolf-sheet.js', 'utf8').includes('Generated by'))
    assert.equal(NPC_SPECIES.wolf.sheet, 'wolf')
    assert.equal(NPC_SPECIES.wolf.sprite, undefined, 'no tile sprite left behind')
    assert.ok(!fs.existsSync('renderer/assets/tiles/npc_wolf.png'), 'the old placeholder tile is gone')
  })
  it('keeps the wolf mostly opaque grey — no magenta survived the key', () => {
    const png = readPng('renderer/assets/npcs/wolf.png')
    let magenta = 0, opaque = 0
    for (let i = 0; i < png.pixels.length; i += 4) {
      if (png.pixels[i + 3] < 128) continue
      opaque++
      const [r, g, b] = [png.pixels[i], png.pixels[i + 1], png.pixels[i + 2]]
      if (r > g + 60 && b > g + 60) magenta++
    }
    assert.ok(opaque > 2000, `opaque pixels: ${opaque}`)
    assert.equal(magenta, 0)
  })
})

describe('drawNpcSheet', () => {
  afterEach(() => _setSheetImage('wolf', undefined))

  it('blits one cell 1.5 tiles wide with the paws on the tile baseline', () => {
    _setSheetImage('wolf', fakeSheet)
    const ctx = recordingCtx()
    assert.equal(drawNpcSheet(ctx, wolfAt(2, 3), 'wolf', 64, 96, S, false), true)
    const draws = ctx.ops.filter(o => o[0] === 'drawImage')
    assert.equal(draws.length, 1)
    const [, img, sx, sy, sw, sh, dx, dy, dw, dh] = draws[0]
    assert.equal(img, fakeSheet)
    assert.deepEqual([sx, sy, sw, sh], [0, 0, SHEET.cellW, SHEET.cellH], 'first walk frame')
    assert.equal(dw, Math.round(S * NPC_SHEETS.wolf.tiles))
    assert.equal(dh, Math.round(dw * SHEET.cellH / SHEET.cellW), 'aspect kept')
    assert.deepEqual([dx, dy], [0, 0], 'drawn at the translated origin')
    const t = ctx.ops.find(o => o[0] === 'translate')
    assert.deepEqual(t.slice(1), [64 + S / 2 - dw / 2, 96 + S - dh])
    assert.ok(!ctx.ops.some(o => o[0] === 'scale'))
  })

  it('facing west mirrors around the cell', () => {
    _setSheetImage('wolf', fakeSheet)
    const ctx = recordingCtx()
    drawNpcSheet(ctx, wolfAt(2, 3), 'wolf', 64, 96, S, true)
    const dw = Math.round(S * 1.5), dh = Math.round(dw * SHEET.cellH / SHEET.cellW)
    assert.deepEqual(ctx.ops.find(o => o[0] === 'translate').slice(1), [64 + S / 2 - dw / 2 + dw, 96 + S - dh])
    assert.deepEqual(ctx.ops.find(o => o[0] === 'scale').slice(1), [-1, 1])
    assert.equal(ctx.ops.filter(o => o[0] === 'save').length, ctx.ops.filter(o => o[0] === 'restore').length)
  })

  it('picks the cell the animation asks for', () => {
    _setSheetImage('wolf', fakeSheet)
    const e = wolfAt(2, 3, { ai: { current: 'hunt_prey' } })
    tickNpcAnim(e, STRIDE.run * 2, 0.016)
    const ctx = recordingCtx()
    drawNpcSheet(ctx, e, 'wolf', 0, 0, S, false)
    const [, , sx, sy] = ctx.ops.find(o => o[0] === 'drawImage')
    assert.equal(sx, 2 * SHEET.cellW)
    assert.equal(sy, SHEET.rows.run.row * SHEET.cellH)
  })

  it('draws a silhouette and no image before the sheet is ready', () => {
    const ctx = recordingCtx()
    drawNpcSheet(ctx, wolfAt(2, 3), 'wolf', 0, 0, S, false)
    assert.ok(!ctx.ops.some(o => o[0] === 'drawImage'))
    assert.ok(ctx.ops.filter(o => o[0] === 'fillRect').length >= 2)
  })

  it('returns false for a species without a sheet', () => {
    assert.equal(drawNpcSheet(recordingCtx(), wolfAt(0, 0), 'deer', 0, 0, S, false), false)
  })
})

describe('drawEntity routes sheet species through the sheet', () => {
  afterEach(() => _setSheetImage('wolf', undefined))
  it('a wolf draws from the sheet, a deer from its tile', () => {
    _setSheetImage('wolf', fakeSheet)
    const ctx = recordingCtx()
    const deerTile = { deer: true }
    drawEntity(ctx, wolfAt(1, 1), 32, 32, S, { npc_deer: deerTile })
    drawEntity(ctx, makeNpc({ species: 'deer', id: 'npc:t:1', x: 1, y: 1 }), 32, 32, S, { npc_deer: deerTile })
    const imgs = ctx.ops.filter(o => o[0] === 'drawImage').map(o => o[1])
    assert.deepEqual(imgs, [fakeSheet, deerTile])
  })
})
