import { describe, it, afterEach } from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import { schemaErrors, defaultParams } from '../renderer/render/monster-rigs/schema.js'
import { RIG_ID, PARAM_SCHEMA, drawMonster, hitHalf, frameFor, _setSheetImage } from '../renderer/render/monster-rigs/serpent.js'
import { SHEET } from '../renderer/assets/monsters/serpent-sheet.js'
import { readPng } from '../tools/png-read.mjs'

function recordingCtx() {
  const target = { ops: [] }
  return new Proxy(target, {
    get(t, k) { if (k in t) return t[k]; return (...a) => { t.ops.push([k, ...a]) } },
    set(t, k, v) { t[k] = v; return true },
  })
}
const pose = (state, over = {}) => ({ t: 1.25, state, stateT: 0.1, facing: 0, speed01: 0, seed: 3, sink: 0, burn: 0, flicker: 0, ...over })
const extremes = which => Object.fromEntries(PARAM_SCHEMA.map(p => [p.key, p.type === 'range' ? p[which] : p.default]))
const P = defaultParams(PARAM_SCHEMA)
const fakeSheet = { complete: true, naturalWidth: SHEET.cellW * 7, naturalHeight: SHEET.cellH * 3 }

describe('serpent rig', () => {
  afterEach(() => _setSheetImage(null))

  it('has a valid schema and id', () => {
    assert.deepEqual(schemaErrors(PARAM_SCHEMA), [])
    assert.equal(RIG_ID, 'serpent')
  })

  it('the generated sheet on disk matches its metadata', () => {
    const png = readPng('renderer/assets/monsters/serpent.png')
    const cols = Math.max(...Object.values(SHEET.rows).map(r => r.frames))
    assert.equal(png.width, SHEET.cellW * cols)
    assert.equal(png.height, SHEET.cellH * Object.keys(SHEET.rows).length)
    assert.ok(png.pixels.some((v, i) => i % 4 === 3 && v === 0), 'sheet has transparent pixels')
    assert.ok(fs.readFileSync('renderer/assets/monsters/serpent-sheet.js', 'utf8').includes('Generated by'))
  })

  for (const state of ['idle', 'hit', 'walk', 'attack', 'death']) {
    it(`draws a silhouette without a sheet in state ${state} at defaults, min and max`, () => {
      for (const params of [P, extremes('min'), extremes('max')]) {
        const ctx = recordingCtx()
        assert.doesNotThrow(() => drawMonster(ctx, params, pose(state), 32))
        assert.ok(ctx.ops.filter(o => o[0] === 'fillRect').length >= 3)
        assert.equal(ctx.ops.filter(o => o[0] === 'save').length, ctx.ops.filter(o => o[0] === 'restore').length)
        assert.ok(!ctx.ops.some(o => o[0] === 'drawImage'))
      }
    })
  }

  it('blits one sheet cell once the image is ready, a cell width across `width` tiles', () => {
    _setSheetImage(fakeSheet)
    const ctx = recordingCtx()
    drawMonster(ctx, P, pose('idle'), 32)
    const draws = ctx.ops.filter(o => o[0] === 'drawImage')
    assert.equal(draws.length, 1)
    const [, img, sx, sy, sw, sh, dx, dy, dw, dh] = draws[0]
    assert.equal(img, fakeSheet)
    assert.equal(sw, SHEET.cellW); assert.equal(sh, SHEET.cellH)
    assert.equal(sy, SHEET.rows.idle.row * SHEET.cellH)
    assert.equal(sx % SHEET.cellW, 0)
    assert.equal(dw, Math.round(P.width * 32))
    assert.equal(dh, Math.round(SHEET.cellH * P.width * 32 / SHEET.cellW))
    assert.equal(dx, -Math.round(dw / 2) + Math.round(P.shift * 32))
    assert.ok(dy + dh <= Math.round(P.waterline * 32) + 3, 'frame bottom sits near the waterline offset')
  })

  it('picks rows by pose: idle still, swim moving, dive by sink', () => {
    assert.equal(frameFor(P, pose('idle')).row, SHEET.rows.idle.row)
    assert.equal(frameFor(P, pose('walk', { speed01: 0.8 })).row, SHEET.rows.swim.row)
    assert.equal(frameFor(P, pose('idle', { speed01: 0.5 })).row, SHEET.rows.swim.row)
    assert.equal(frameFor(P, pose('idle', { sink: 0.01 })).row, SHEET.rows.dive.row)
  })

  it('dive frames advance with sink and reverse on the way up', () => {
    const n = SHEET.rows.dive.frames
    const seq = [0.05, 0.3, 0.6, 0.95].map(s => frameFor(P, pose('idle', { sink: s })).frame)
    for (let i = 1; i < seq.length; i++) assert.ok(seq[i] >= seq[i - 1], String(seq))
    assert.equal(frameFor(P, pose('idle', { sink: 1 })).frame, n - 1)
    assert.equal(frameFor(P, pose('idle', { sink: 0.05 })).frame, 0)
  })

  it('idle animates through every frame over time', () => {
    const seen = new Set()
    for (let t = 0; t < 2; t += 1 / 60) seen.add(frameFor(P, pose('idle', { t })).frame)
    assert.equal(seen.size, SHEET.rows.idle.frames)
  })

  it('flips when facing east (the art faces west)', () => {
    const east = recordingCtx(), west = recordingCtx()
    drawMonster(east, P, pose('idle', { facing: 0 }), 32)
    drawMonster(west, P, pose('idle', { facing: Math.PI }), 32)
    assert.ok(east.ops.some(o => o[0] === 'scale' && o[1] === -1))
    assert.ok(!west.ops.some(o => o[0] === 'scale' && o[1] === -1))
  })

  it('hitHalf stays within the nav-supported range', () => {
    for (const params of [P, extremes('min'), extremes('max')]) {
      const h = hitHalf(params)
      assert.ok(h >= 8 && h <= 28, String(h))
    }
  })
})
