import { describe, it, afterEach } from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import { schemaErrors, defaultParams } from '../renderer/render/monster-rigs/schema.js'
import { RIG_ID, PARAM_SCHEMA, drawMonster, hitHalf, frameFor, _setSheetImage } from '../renderer/render/monster-rigs/wraith.js'
import { SHEET } from '../renderer/assets/monsters/wraith-sheet.js'
import { readPng } from '../tools/png-read.mjs'

function recordingCtx() {
  const target = { ops: [], globalAlpha: 1 }
  return new Proxy(target, {
    get(t, k) { if (k in t) return t[k]; return (...a) => { t.ops.push([k, ...a]) } },
    set(t, k, v) { t[k] = v; return true },
  })
}
const pose = (state, over = {}) => ({ t: 0.9, state, stateT: 0.3, facing: 0, speed01: 0, seed: 11, sink: 0, burn: 0, flicker: 0, ...over })
const extremes = which => Object.fromEntries(PARAM_SCHEMA.map(p => [p.key, p.type === 'range' ? p[which] : p.default]))
const P = defaultParams(PARAM_SCHEMA)
const fakeSheet = { complete: true, naturalWidth: SHEET.cellW * 5, naturalHeight: SHEET.cellH * 2 }

describe('wraith rig', () => {
  afterEach(() => _setSheetImage(null))

  it('has a valid schema and id', () => {
    assert.deepEqual(schemaErrors(PARAM_SCHEMA), [])
    assert.equal(RIG_ID, 'wraith')
  })

  it('the generated sheet on disk matches its metadata', () => {
    const png = readPng('renderer/assets/monsters/wraith.png')
    const cols = Math.max(...Object.values(SHEET.rows).map(r => r.frames))
    assert.equal(png.width, SHEET.cellW * cols)
    assert.equal(png.height, SHEET.cellH * Object.keys(SHEET.rows).length)
    assert.equal(SHEET.rows.float.frames + SHEET.rows.dissolve.frames, 8, 'the eight-frame loop')
    assert.ok(png.pixels.some((v, i) => i % 4 === 3 && v === 0), 'sheet has transparent pixels')
    assert.ok(fs.readFileSync('renderer/assets/monsters/wraith-sheet.js', 'utf8').includes('Generated by'))
  })

  for (const state of ['idle', 'hit', 'walk', 'attack', 'death']) {
    it(`draws a silhouette without a sheet in state ${state} at defaults, min and max`, () => {
      for (const params of [P, extremes('min'), extremes('max')]) {
        const ctx = recordingCtx()
        assert.doesNotThrow(() => drawMonster(ctx, params, pose(state), 32))
        assert.ok(ctx.ops.filter(o => o[0] === 'fillRect').length >= 3)
        assert.equal(ctx.ops.filter(o => o[0] === 'save').length, ctx.ops.filter(o => o[0] === 'restore').length)
        assert.ok(!ctx.ops.some(o => o[0] === 'drawImage'))
      }
    })
  }

  it('blits one sheet cell once the image is ready, a cell height across `height` tiles', () => {
    _setSheetImage(fakeSheet)
    const ctx = recordingCtx()
    drawMonster(ctx, P, pose('idle'), 32)
    const draws = ctx.ops.filter(o => o[0] === 'drawImage')
    assert.equal(draws.length, 1)
    const [, img, sx, sy, sw, sh, dx, dy, dw, dh] = draws[0]
    assert.equal(img, fakeSheet)
    assert.equal(sw, SHEET.cellW); assert.equal(sh, SHEET.cellH)
    assert.equal(sy, SHEET.rows.float.row * SHEET.cellH)
    assert.equal(sx % SHEET.cellW, 0)
    assert.equal(dh, Math.round(P.height * 32))
    assert.equal(dw, Math.round(SHEET.cellW * P.height * 32 / SHEET.cellH))
    assert.equal(dx, -Math.round(dw / 2))
    assert.ok(dy < -dh / 2, 'lift raises the frame above the cell centre')
  })

  it('floats through every loop frame over time', () => {
    const seen = new Set()
    for (let t = 0; t < 2; t += 1 / 60) seen.add(frameFor(P, pose('walk', { t })).frame)
    assert.equal(seen.size, SHEET.rows.float.frames)
    assert.equal(frameFor(P, pose('walk')).row, SHEET.rows.float.row)
  })

  it('a strong flicker unravels it: dissolve frames advance with flicker', () => {
    assert.equal(frameFor(P, pose('walk', { flicker: 0.2 })).row, SHEET.rows.float.row)
    const seq = [0.4, 0.7, 1.0].map(f => frameFor(P, pose('walk', { flicker: f })))
    assert.ok(seq.every(s => s.row === SHEET.rows.dissolve.row))
    assert.equal(seq[0].frame, 0)
    assert.equal(seq[2].frame, SHEET.rows.dissolve.frames - 1)
    for (let i = 1; i < seq.length; i++) assert.ok(seq[i].frame >= seq[i - 1].frame)
  })

  it('death plays the dissolve row through and fades out', () => {
    assert.equal(frameFor(P, pose('death', { stateT: 0 })).frame, 0)
    assert.equal(frameFor(P, pose('death', { stateT: 0.69 })).frame, SHEET.rows.dissolve.frames - 1)
    _setSheetImage(fakeSheet)
    const ctx = recordingCtx()
    drawMonster(ctx, P, pose('death', { stateT: 0.35 }), 32)
    assert.ok(ctx.globalAlpha < 1 || ctx.ops.some(o => o[0] === 'restore'), 'alpha lowered inside save/restore')
  })

  it('flips when facing west', () => {
    const west = recordingCtx(), east = recordingCtx()
    drawMonster(west, P, pose('idle', { facing: Math.PI }), 32)
    drawMonster(east, P, pose('idle', { facing: 0 }), 32)
    assert.ok(west.ops.some(o => o[0] === 'scale' && o[1] === -1))
    assert.ok(!east.ops.some(o => o[0] === 'scale' && o[1] === -1))
  })

  it('hitHalf stays within the nav-supported range', () => {
    for (const params of [P, extremes('min'), extremes('max')]) {
      const h = hitHalf(params)
      assert.ok(h >= 8 && h <= 28, String(h))
    }
  })
})
